### ISSUE TITLE
sqlite parameta for shemata missing, presetting is wrong - reopen as not fixed yet.

### ISSUE THREAD

**Issue by LooOOooM** [sensson/puppet-powerdns#100]
with refference to the non fixed issue https://github.com/sensson/puppet-powerdns/issues/97 :

@ju5t Like it or not. Fakt is that this bug is still present, so there is no reason to close of this bugreport.
Also Fakt is that this bug has been fixed by me already (btw. on the fly, in my free time, mate)

Compared to "my ping" closing of a present bug is even more "unfriendly behaviour",- don't you think so, because this is propertly not only hitting me, but also other people within the community waiting for this fix, not beeing able to fix thereself.

So please close that bug by finaly merging it into a new offical puppet forge version, rather then beeing yourself kind of "unfriedly". At lease reopen issue 97, because it is not fixed, yet.

--------------------------------------------------

@LooOOooM you do know that this is very unfriendly behaviour in any open source project, right? This is a project where we spend our free time on. It's not commercial, nobody earns anything or gets paid to make this.

We appreciate your work, but pinging or asking for updates is something we do not want to see in our projects.

We will be releasing this. I can't tell you when. For now, I will be closing this issue. 

_Originally posted by @ju5t in https://github.com/sensson/puppet-powerdns/issues/97#issuecomment-806499342_

**Comment by ju5t** [comment]
Again, this is an open source effort where we spend our free time in an attempt to contribute back to the community. This is not a business where we get paid by the people who use our open source software. We don't want it to be either.

Like it or not, but we have no obligation whatsoever to release things immediately. It's not up to you to decide.

> Compared to "my ping" closing of a present bug is even more "unfriendly behaviour",- don't you think so, because this is propertly not only hitting me, but also other people within the community waiting for this fix, not beeing able to fix thereself.

The bug itself has been solved. It has been merged (have you even checked that?!) and it is ready to be released. We just haven't done so. Asking for new releases is not how it works. If other people are hit by this bug, they have no choice but to wait for a new release OR use the develop branch of this repository. That's just the way it is until it's on the Forge.

Again, pinging or opening new issues like you did now is not the way things work and is not appreciated throughout the entire open source community. So don't. This issue will be closed.
