### ISSUE TITLE
support puppetlabs-stdlib 6.0.0 and higher

### ISSUE THREAD

**Issue by hpkunz** [sensson/puppet-powerdns#105]
I wonder if it would be possible to support higher version of puppetlabs-stdlib.

many thanks,
hp

**Comment by ju5t** [comment]
@hpkunz feel free to open a PR to bump versions. Please do check out [development guidelines](https://github.com/sensson/puppet-powerdns#development) before doing so.

**Comment by saz** [comment]
This issue has been resolved in develop with the merge of #111
