### ISSUE TITLE
Bug: postgres schema file not found Rocky Linux

### ISSUE THREAD

**Issue by imp1sh** [sensson/puppet-powerdns#116]
Hi,
in Rocky Linux 8 the schema file for postgresql cannot be found.
This is where the file is located:
`/usr/share/doc/pdns-backend-postgresql/schema.pgsql.sql`
and this is where the module searches for it:
`pgsql_schema_file = '/usr/share/doc/pdns-backend-postgresql-4.?.?/schema.pgsql.sql'`

Honestly I don't know if it might be Rocky related but I'm convinced that this is the same problem with RedHat and CentOS.

This is the error message:
```
Error: Error executing SQL; psql returned pid 3720060 exit 1: '/usr/share/doc/pdns-backend-postgresql-4.?.?/schema.pgsql.sql: No such file or directory
'
Error: /Stage[main]/Powerdns::Backends::Postgresql/Postgresql_psql[Load SQL schema]/command: change from 'notrun' to '\i /usr/share/doc/pdns-backend-postgresql-4.?.?/schema.pgsql.sql' failed: Error executing SQL; psql returned pid 3720060 exit 1: '/usr/share/doc/pdns-backend-postgresql-4.?.?/schema.pgsql.sql: No such file or directory
'
```

**Comment by ju5t** [comment]
@imp1sh thanks for opening an issue. We're running on CentOS 8 and have not seen similar problems before. But you can override it if needed.

As we don't have a system that runs PostgreSQL and Rocky 8, if you could PR a fix that would be very appreciated!

**Comment by imp1sh** [comment]
I could try to fix that but that would mean I need to change the switch-cache statement away from ['os']['family'] to ['os']['name']. I cannot foresee what other consequences this change would have. Especially because you cover other distributions I can not  test, like Debian and FreeBSD.
['os']['family'] is also 'RedHat' in Rocky but 'Rocky' for ['os']['name'].

**Comment by ju5t** [comment]
@imp1sh it might be possible to use a nested case structure, but I'm not sure. That would probably be the simplest and cleanest solution.

Or a simple if-statement below the case-statement to override it could be ok too. An if-statement would avoid a lot of code repetition, but it's not like there is no repetition in that file already.

Bottom line: I don't necessarily think there is a wrong decision here.
