### ISSUE TITLE
instal: apt and mysql problems

### ISSUE THREAD

**Issue by Boran** [sensson/puppet-powerdns#12]
Hi,  I'm trying the module with a simple
class { 'powerdns': db_password => 'dbpass', db_root_password => 'dbrootpass',}

But it does not like the mysql and apt modules on the puppet master:
`Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid parameter create_root_my_cnf on Class[Mysql::Server] at /etc/puppet/environments/production/modules/powerdns/manifests/backends/mysql.pp:49 on node foo

Error 400 on SERVER: Invalid parameter id on Apt::Key[powerdns] at /etc/puppet/environments/production/modules/powerdns/manifests/repo.pp:49 

Invalid parameter architecture on Apt::Source[powerdns] at /etc/puppet/environments/production/modules/powerdns/manifests/repo.pp:60`

So I made a few changes to how mysql apt::source and apt:.key are called. Also had to install mysql-client package. 

But even then 
`apt-key adv --keyserver 'https://repo.powerdns.com/FD380FBB-pub.asc' --recv-keys 'FD380FBB'
Executing: /tmp/tmp.BsUyvDCsbd/gpg.1.sh --keyserver
https://repo.powerdns.com/FD380FBB-pub.asc
--recv-keys
FD380FBB
gpg: requesting key FD380FBB from https server repo.powerdns.com
gpgkeys: protocol `https' not supported
gpg: no handler for keyserver scheme `https'
gpg: keyserver receive failed: keyserver error`

I guess it is all down to the exact versions of depending modules one uses? Any suggestions?

**Comment by ju5t** [comment]
Which versions of the apt and mysql Puppet modules are you using? Do they match the dependencies that are listed in metadata.json?

**Comment by ju5t** [comment]
@Boran I'm afraid I can't reproduce the problem on our end. Since I haven't heard from you I'm closing this issue until further details are given.
