### ISSUE TITLE
Install PowerDNS version 4.7.x

### ISSUE THREAD

**Issue by apxela** [sensson/puppet-powerdns#145]
Hi, we would like to use this module to install the latest available version of PowerDNS (currently 4.7) but when trying to do so it seems that the module is only prepared to support up to version 4.2.

When I try it I get this error:

`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Class[Powerdns]: parameter 'version' expects a match for Enum['4.0', '4.1'], got '4.7' at /etc/puppetlabs/code/environments/test4/manifests/site.pp:1:1 on node nc-ns-master-test-01.int.netcentric.biz
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run`

I don't know if I'm missing something, but is there any way I can get higher versions?

Thank you very much and best regards

**Comment by jmcnatt** [comment]
Wondering if it's worth putting these constraints on the version parameter altogether.  Not having this strict versioning would allow the module to be used on newer versions without needing to go in and add the value in the `Enum` each time one is released.

**Comment by jmcnatt** [comment]
Looks like this was fixed in #132.  We just need a version bump.

**Comment by ju5t** [comment]
@jmcnatt this should all be sorted now.
