### ISSUE TITLE
powerdns::config should allow empty value on only-notify 

### ISSUE THREAD

**Issue by Poil** [sensson/puppet-powerdns#15]
If you do not need to NOTIFY the slaves defined in the NS records (e.g. you are using another method to distribute the zone data to the slaves), then set only-notify to an empty value and specify the notification targets explicitly using also-notify and/or ALSO-NOTIFY domain metadata to avoid this potential bottleneck.

Proposal fix :
```
  if $value == '' and !$setting in ['gmysql-dnssec', 'only-notify'] { fail("Value can't be empty.") }
```

**Comment by ju5t** [comment]
Thanks, this is in fact a bug and we should allow for empty values when the setting is `only-notify`. If you can you are free to open a pull request -- if not I will try to get this implemented as soon as possible.

**Comment by ju5t** [comment]
This commit should solve the issue you reported. I've also added tests for it while I was at it. @Poil are you able to check this on one of your systems?

If all tests pass I'll merge it to master and prepare a new release.

**Comment by Poil** [comment]
Yes that's good :)

Perhaps you can add in the fail message the $title of the key to know which one fail

Thanks

**Comment by ju5t** [comment]
Good suggestion. Even though Puppet should tell you which resource fails it's not a major change. I've made sure it includes `$setting` as `$title` would be part of what Puppet returns.
