### ISSUE TITLE
[Bug] Improper sorting of forward_zones causes broken forwarding configuration

### ISSUE THREAD

**Issue by akremer** [sensson/puppet-powerdns#168]
The following line:

https://github.com/sensson/puppet-powerdns/blob/8557cd21064ac97160b79fe8e89576ab442c7265/templates/forward_zones.conf.erb#L1

Causes the keys in forward_zones to be lexographically sorted. If you have a catchall forwarder set up, for example:

`'+.'        => '1.1.1.1;8.8.8.8;8.8.4.4',`

The `.sort` command will always list the catchall first, causing the powerdns recursor to never see other entries in the forward_zones file.

Removing the `.sort` leaves the keys as originally specified in the configuration, ensuring the forwarding order is kept intact.

**Comment by ju5t** [comment]
I'm OK with removing `.sort` here. Can you send a PR for it?
