### ISSUE TITLE
README.md mentions 'listen-address' instead of 'local-address'

### ISSUE THREAD

**Issue by batmac** [sensson/puppet-powerdns#18]
README.md examples mention it, but 'listen-address' option doesn't exist, I think you mean 'local-address'

`pdns_recursor[6748]: Sep 22 14:51:08 Exception: Trying to set unknown parameter 'listen-address'`

**Comment by ju5t** [comment]
Thanks for the report. You're right. This should be `local-address`. I'll fix this in the next release.
