### ISSUE TITLE
Remote MySQL Backend

### ISSUE THREAD

**Issue by ehw-sky** [sensson/puppet-powerdns#19]
This module doesn't seem to support MySQL backends located on other servers.

`powerdns::backends::mysql::create_table` has a dependency on `Service['mysqld']` 

Is that the case, or am I misinterpreting this?

**Comment by ju5t** [comment]
You're right. 

It uses `puppetlabs/mysql` to do some of its heavy lifting. As such, a rewrite to support external databases could be harder than it sounds.

It would probably be faster to provision the external database by hand and have this module set the required configs for you instead. It should be enough to copy/paste the `powerdns::config` blocks from https://github.com/sensson/puppet-powerdns/blob/master/manifests/backends/mysql.pp and include the `pdns-backend-mysql` package.

If you can and have the time you are definitely encouraged to open a pull request. 

I'll leave this open for the moment.
