### ISSUE TITLE
powerdns::config ensure => absent should remove setting and shouldn't require 'value'

### ISSUE THREAD

**Issue by alexjfisher** [sensson/puppet-powerdns#20]
At the moment, it's not possible to purge a configuration setting.

**Comment by ju5t** [comment]
Thanks for your work so far @alexjfisher.

Once you're ready to merge this I need to have a look at #21 first. The current tests have a few errors that need to be ironed out.

**Comment by ju5t** [comment]
I've just pushed the fixes for the errors the tests were giving.

**Comment by alexjfisher** [comment]
@ju5t Hi!  Sorry for the delay, I took a couple of weeks off.  Happy New Year!  Should I be targeting the 'develop' or 'master' branch when I create a PR? (I'm going to write some spec tests first.)

**Comment by alexjfisher** [comment]
and I guess since https://github.com/sensson/puppet-powerdns/commit/08830026728ee7814ef9893873b91cf20c091a08 I can also use Puppet 4 parameter data type validation?

**Comment by ju5t** [comment]
No worries and happy new year to you too!

The develop branch would be the best target. It is the most up to date, it contains everything that's due to be released. As to Puppet 4 validation: yes, absolutely.

**Comment by ju5t** [comment]
This is now merged into develop.
