### ISSUE TITLE
Update for powerdns 4.1

### ISSUE THREAD

**Issue by alexjfisher** [sensson/puppet-powerdns#30]
`repo.pp` needs updating and I think the mysql default schema is slightly different. See https://doc.powerdns.com/authoritative/upgrading.html#upgrade-notes

Maybe a new top level `$version` parameter needs to be added?

**Comment by ju5t** [comment]
If we add it we should make it so several database schemas are supported too. And what about if you switch from 4.0 to 4.1, should we handle the upgrade too? I'm a little in doubt as to what consequences `$version` should have.

**Comment by ngoduykhanh** [comment]
+1 for new version. I think the schema upgrading should be taken care manually, not from this module itself.

**Comment by ju5t** [comment]
If we're going to support a `$version` parameter we should version the templates too. I would probably create a folder per version in `templates` and reference that when the initial setup runs.

**Comment by ju5t** [comment]
We should be good to go on 4.1 next week.
