### ISSUE TITLE
powerdns::backends::mysql should set gmysql-host

### ISSUE THREAD

**Issue by alexjfisher** [sensson/puppet-powerdns#31]
`db_host` is only being using in the `mysql::db` resource here. https://github.com/sensson/puppet-powerdns/blob/develop/manifests/backends/mysql.pp#L58

I think the following is missing.
```puppet
powerdns::config { 'gmysql-host':
    ensure  => present,
    setting => 'gmysql-host',
    value   => $::powerdns::db_host,
    type    => 'authoritative',
  }
````

**Comment by alexjfisher** [comment]
We should then be able to close https://github.com/sensson/puppet-powerdns/issues/19?

**Comment by ju5t** [comment]
I agree. Together with the `$backend_install` parameter it should be enough to close #19.

**Comment by ju5t** [comment]
@alexjfisher This is a breaking change for those who already have their database configured elsewhere as it would overwrite `gmysql-host`. This should only happen for those who are using develop as on other environments having `powerdns::db_host` set was already required.

I'll add this today.

**Comment by ju5t** [comment]
For some reason my branch included too many commits. I've removed the branch and I'll start over.
