### ISSUE TITLE
powerdns::config only accepts String

### ISSUE THREAD

**Issue by ju5t** [sensson/puppet-powerdns#37]
Some configuration settings (such as ports) should be specified as an integer. We only accept a string value at the moment in `powerdns::config`. This is a regression of #26.

**Comment by alexjfisher** [comment]
I think the regression was actually in https://github.com/sensson/puppet-powerdns/pull/22
Either way, my mistake. Sorry!

**Comment by ju5t** [comment]
Ah yes, no worries though. I've added a test for it so we should be covered in the future.
