### ISSUE TITLE
Module requires an old version of puppetlabs/apt

### ISSUE THREAD

**Issue by kasimon** [sensson/puppet-powerdns#38]
Your module requires `puppetlabs/apt (>=2.0.0 < 3.0.0)` but the current version of puppetlabs/apt is `4.5.1`. Please update the requirement, otherwise `puppet module install` installs an old version of the powerdns module.

**Comment by ju5t** [comment]
Thanks for the report @kasimon. 

Tests on puppetlab/apt 4.5.1 are looking good for both spec as acceptance tests. I've pushed an update of `metadata.json` and `.fixtures.yml` to develop and we'll release a new version, hopefully tomorrow by the end of the day.

**Comment by ju5t** [comment]
Rubocop 0.53 started checking on empty comments in our tests and apparently my local system was still on 0.52. That's the reason https://github.com/sensson/puppet-powerdns/commit/d48f3e9c3114cd84df1484193372e0bbd6a43466 didn't pass. This is solved in a different commit, unrelated to this issue.

**Comment by kasimon** [comment]
Thanks a lot for the fast reply! Looking forward to the new release.

**Comment by ju5t** [comment]
I've just released 1.1.0.

**Comment by kasimon** [comment]
Awesome, thanks!
