### ISSUE TITLE
Forge module contains lib/facter/powerdns_version.rb with error

### ISSUE THREAD

**Issue by wardhus** [sensson/puppet-powerdns#44]
Hi,

I can't find the code here on GitHub but the Forge contains a version with a lib/facter/powerdns_version.rb file that contains an error. Should be Facter instead of Factor I guess.

Kind regards,
Ward Hus

**Comment by ju5t** [comment]
@wardhus thanks for reporting this. This file shouldn't be in the release on the Forge. I've taken down 1.2.1 and released 1.2.2 to address this error.
