### ISSUE TITLE
Fresh install of powerdns 4.1 fails on Debian

### ISSUE THREAD

**Issue by mstinsky** [sensson/puppet-powerdns#47]
Hey,

I tested the new 1.2.3 version with a fresh install of powerdns 4.1 and it fails because of the following reason. Powerdns 4.1 ships with the following new configuration file on a debian installation: /etc/powerdns/pdns.d/pdns.local.gmysql.conf, which leads to having 2 mysql backends configured, one through this module in /etc/powerdns/pdns.conf and one in the mentioned config, this leads to the service failing to start. 

For now I fixed this by deleting the new config file after installing pdns-backend-mysql in powerdns::backends::mysql.
A better solution in my opinion would be to add a new config type "database" to powerdns:config and use this to configure the database in the "new" config file that is installed through the debian package. What would be your suggestion ? If this is also your prefered way I could see if I can make a pull request happen on the weekend for this.

Best Regards
Max

**Comment by ju5t** [comment]
@mstinsky that's strange. I do actually test this. It's not part of what runs through Travis CI yet but there are acceptance tests for Debian. 

```
debian-82-x64 10:29:37$ /bin/sh -c systemctl\ is-active\ pdns
  active
```

What errors do you get? We can add them to the acceptance tests for all operating systems.

Personally I would remove the file in `powerdns::backends::mysql`. If you add a `database` type to `powerdns::config` you would have to implement this for all operating systems. `/etc/powerdns/pdns.d/` doesn't exist on CentOS for example.

**Comment by mstinsky** [comment]
The error I get is the following:
`May 03 09:01:09 Fatal error: Refusing to launch multiple backends with the same name 'gmysql', verify all 'launch' statements in your configuration`.
And my assumption is that this happens because the postinst of pdns-backend-mysql creates /etc/powerdns/pdns.d/pdns.local.gmysql.conf.

Strange that you don't get this error on your tests.

**Comment by mstinsky** [comment]
@ju5t sorry for that ... I found the issue, I was missing lsb-release in my lxc container so the apt source file was broken and it got the powerdns package from the debian repos which had this database config file in it. After fixing the lsb-relase thing the repos are correct and the package is installed from the powerdns repo which does not has the config file.

**Comment by ju5t** [comment]
@mstinsky no problem, I'm glad you got it working.
