### ISSUE TITLE
pgsql_schema_file is not working on CentOS-servers

### ISSUE THREAD

**Issue by ju5t** [sensson/puppet-powerdns#55]
For some reason this passed our initial acceptance tests on CentOS. `postgresql_psql` doesn't like the  question marks in our file name. 

```
Error: /Stage[main]/Powerdns::Backends::Postgresql/Postgresql_psql[Load SQL schema]/command: change from notrun to \i /usr/share/doc/pdns-backend-postgresql-4.?.?/schema.pgsql.sql failed: Error executing SQL; psql returned pid 5877 exit 1: '/usr/share/doc/pdns-backend-postgresql-4.?.?/schema.pgsql.sql: No such file or directory
```

As this files changes in each minor release it could easily break if we hardcoded our files for CentOS so that's not a great option.

**Comment by ju5t** [comment]
This is not as easy as it sounds unfortunately.

* `file` doesn't allow wildcards (which makes sense).
* A fact that gets the current PowerDNS-version would be false until PowerDNS is installed. Facts are populated only once before the Puppet code runs. 
* A custom provider/type should but introduces overhead (as in code to manage).

Creating a fact is easy but it wouldn't populate the database until the second run.

**Comment by olevole** [comment]
@ju5t maybe as workaround:

```
      exec { 'Load SQL schema':
        command => "/usr/bin/env psql postgres://${::powerdns::db_username}:${::powerdns::db_password}@${::powerdns::db_host}:5432/${::powerdns::db_name} < ${::powerdns::pgsql_schema_file}",
        unless => "/usr/bin/env psql postgres://${::powerdns::db_username}:${::powerdns::db_password}@${::powerdns::db_host}:5432/${::powerdns::db_name} -t -c \"SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'domains'\" | grep -q 1",
        require          => Postgresql::Server::Db[$::powerdns::db_name],
      }
```

not ideal, but can be used up to a better solution with PowerDNS version from facts
