### ISSUE TITLE
failing on OEL linux

### ISSUE THREAD

**Issue by dannycooke** [sensson/puppet-powerdns#64]
Hi 
for a week we have been trying to use this module on OEL linux 7.4 and can't seem to get past this puppet failure. tried many different configurations including installing mysql separately first but to no avail

puppet settings:-
classes
  - powerdns

powerdns::db_root_password: 'Password1'
#backend_install: false
powerdns::backend_install: true
powerdns::db_username: 'pdns'
powerdns::db_password: 'Password1'
powerdns::recursor: true
powerdns::custom_repo: false
powerdns::recursor::package_ensure: 'latest'
powerdns::authoritative::package_ensure: 'latest'

powerdns::auth::config:
  gmysql-dnssec:
    value: ''
  local-address:
    value: '127.0.0.1'
  api:
    value: 'yes'

powerdns::auth::config:
  local-address-auth:
    setting: 'local-address'
    value: '127.0.0.1'
powerdns::recursor::config:
  local-address-recursor:
    setting: 'local-address'
    value: '127.0.0.2'

failure output

# puppet agent -t
Info: Using configured environment 'dev'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: Loading facts
Info: Caching catalog for server1
Info: Applying configuration version '1543425800'
Notice: /Stage[main]/Autofs/Exec[autofs on]/returns: executed successfully
Info: /Stage[main]/Autofs/Exec[autofs on]: Scheduling refresh of Exec[autofs rc3 kill last]
Info: /Stage[main]/Autofs/Exec[autofs on]: Scheduling refresh of Exec[autofs rc5 kill last]
Notice: /Stage[main]/Autofs/Exec[autofs rc3 kill last]: Triggered 'refresh' from 1 event
Notice: /Stage[main]/Autofs/Exec[autofs rc5 kill last]: Triggered 'refresh' from 1 event
Notice: /Stage[main]/Mysql::Server::Service/Service[mysqld]/ensure: ensure changed 'stopped' to 'running'
Info: /Stage[main]/Mysql::Server::Service/Service[mysqld]: Unscheduling refresh on Service[mysqld]
Error: Failed to apply catalog: Execution of '/bin/mysql -NBe SELECT CONCAT(User, '@',Host) AS User FROM mysql.user' returned 1: ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)

**Comment by ju5t** [comment]
If you want to install MySQL yourself (or from a different manifest) you need to set `$::powerdns::backend_install` to false. Otherwise you will get errors.

The following error:

```
Error: Failed to apply catalog: Execution of '/bin/mysql -NBe SELECT CONCAT(User, '@',Host) AS User FROM mysql.user' returned 1: ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
```

Seems as if the MySQL server has been installed prior to running Puppet. Or perhaps OEL installs it using a default username and password, although I don't think it does.

I'll try to find some time to test this using Vagrant. There is a 7.5 box available on https://yum.oracle.com/boxes.

In the meantime could you try installing MySQL manually and use the before mentioned parameters?

**Comment by ju5t** [comment]
I'm closing this issue due as it's been inactive for a while.

**Comment by jameskirsop** [comment]
FWIW, I'm seeing this on a clean install with a correct root password (tested by calling `mysql -u root -p`) on CentOS 7.

MySQL (actually mariadb) was already installed by a different puppet module, so I'm yet unsure if that's got something to do with it.
