### ISSUE TITLE
Multiple backends

### ISSUE THREAD

**Issue by EarthDevour** [sensson/puppet-powerdns#66]
PowerDNS can run with multiple backends, and this module doesn't provide any way of doing it.

For eg:
launch=gmysql, pipe

Package:
pdns-backend-pipe.x86_64 : Pipe backend for pdns

It is possible to have other combinations of backends.

**Comment by ju5t** [comment]
It is, but;

> Do note that multi-backend behaviour is not specified and might change between versions.

Ref: [PowerDNS FAQ](https://doc.powerdns.com/authoritative/appendices/FAQ.html#can-i-launch-multiple-backends-simultaneously)

Unless someone is willing to raise a pull request for it, essentially rewriting large parts of the module and its backends, I must be honest here that this won't get much priority from us. It will take a lot of time to implement this.

**Comment by EarthDevour** [comment]
Understood...
Looks like I would need to insert those using file_line. While it is can be acceptable workaround it is not that cool powerdns server will be reloaded 2 times :) 
Thanks anyway. I'll raise PR if I'll decide to integrate this into module.

**Comment by ju5t** [comment]
It's not that easy. I assume you want to manage `launch` with `file_line`? If that's the plan you can't really use any of the backends included as they will try to control `launch` too.

To change this behaviour we would have to drop `powerdns::config { 'launch': }` from all backends, move it into `powerdns::authoritative` and rewrite the current `case` to an array or similar so it can support multiple backends. It also affects `$powerdns::backend` in `init.pp`.

That's all I can think of right now--I could be missing something here.

**Comment by EarthDevour** [comment]
Thanks, I'll let you know if I will come up with "usable" solution for this, merry Christmas !
