### ISSUE TITLE
Switch custom_repo to manage_package_repo

### ISSUE THREAD

**Issue by ju5t** [sensson/puppet-powerdns#67]
The `custom_repo` parameter was added from the perspective of the module's behaviour at that time; it allows you to override the default repo--but the default repo is the one from PowerDNS instead of the operating system.

Other modules seem to favour the operating system. They use `manage_package_repo` to include the repositories of the software they are managing. As PowerDNS depends on EPEL (on RHEL) by default, this parameter should change as well.

This is a breaking change and potentially one that impacts people if they don't notice it.

It was originally raised in PR #65 but it requires a more thorough change to implement this. We should probably change this, but as it is a breaking change some more thoughts on this would be appreciated.

**Comment by c33s** [comment]
not stale

**Comment by ju5t** [comment]
@c33s we currently don't have the time to build a solution for this. I'm not sure if you can find the time for it?

**Comment by c33s** [comment]
@ju5t already [opened a PR][1] which was rejected and instead this issue was created. as i use only debian, i don't think i can help with the tasks required for redhat.

[1]: https://github.com/sensson/puppet-powerdns/pull/65

**Comment by ju5t** [comment]
Your PR changed how custom repo should be interpreted. I think we should use a manage package repo variable, which is a breaking change, but it is the best solution if you ask me. 

I'm happy to leave this open for a while, but our time is limited to PR this.
