### ISSUE TITLE
Upgrade dependencies for Puppet 6 support

### ISSUE THREAD

**Issue by schlitzered** [sensson/puppet-powerdns#68]
Please update the package dependencies to allow Puppet & Support

**Comment by ju5t** [comment]
@schlitzered feel free to submit a PR for this.

**Comment by ju5t** [comment]
This depends on #63 and https://tickets.puppetlabs.com/browse/MODULES-8158. Until this has been solved the only solution is to drop support for Puppet 4.7.

**Comment by schlitzered** [comment]
thx, i will take a look at this tomorrow

**Comment by schlitzered** [comment]
looks fine to me

**Comment by ju5t** [comment]
Thanks and I apologize for the delay. This is now part of version 1.6.0.
