### ISSUE TITLE
Redhat support

### ISSUE THREAD

**Issue by rodrigomgm** [sensson/puppet-powerdns#7]
Will you be able to include support to redhat? if you tested it on centos, then shouldnt be any issue allowing Redhat.

**Comment by ju5t** [comment]
There are no packages available for RHEL yet on https://repo.powerdns.com. 

It should work with the rpm's from CentOS but our installation is currently based on packages being available in a repository. Having said that we don't have developer access to RHEL and neither do we have any RHEL servers running that we could use to test this module on.

**Comment by rodrigomgm** [comment]
It may not provide a specific repo for rhel, but the rpm are "el6" or "el7", and your module hard-code the "centos" in the URL so it works regardless of which OS you are using.

I forked out your project and added redhat to the case statements and it worked. I tested on RHEL 6.8 x86_64.

Also, do you have any plan to include support for postgres?

Regards
Rodrigo

________________________________
De: ju5t <notifications@github.com>
Enviado: quinta-feira, 5 de janeiro de 2017 01:38
Para: sensson/puppet-powerdns
Cc: rodrigomgm; Author
Assunto: Re: [sensson/puppet-powerdns] Redhat support (#7)


There are no packages available for RHEL yet on https://repo.powerdns.com.

PowerDNS repositories<https://repo.powerdns.com/>
repo.powerdns.com
These repositories are split between the different pieces of PowerDNS software: PowerDNS Authoritative Server; PowerDNS Recursor; dnsdist



It should work with the rpm's from CentOS but our installation is currently based on packages being available in a repository. Having said that we don't have developer access to RHEL and neither do we have any RHEL servers running that we could use to test this module on.

-

**Comment by ju5t** [comment]
You're always welcome to send in a pull request and add some tests for this case if you can. 

About PostgreSQL: a backend in this module only sets some defaults and tries to install the required software (e.g. MySQL) for you. It should be non-blocking to install and configure PostgreSQL as a backend manually. 

We haven't made any plans when we will exactly include other backends but we definitely will in the future. I've created issue #8 for this.

**Comment by ju5t** [comment]
This should be solved by #35.
