### ISSUE TITLE
Debian pinning is lower than the default

### ISSUE THREAD

**Issue by geoffr** [sensson/puppet-powerdns#74]
Hi,

Could the pinning priority for Debian become a parameter so that it can be adjusted to be higher than the priority set as the default?  At the moment I get the following even though the powerdns::version is set to '4.2'

pdns-recursor:
  Installed: 4.1.11-1+deb10u1
  Candidate: 4.1.11-1+deb10u1
  Version table:
     4.2.2-1pdns.buster 600
        500 http://repo.powerdns.com/debian buster-rec-42/main amd64 Packages
 *** 4.1.11-1+deb10u1 990
        990 http://security.debian.org buster/updates/main amd64 Packages
        100 /var/lib/dpkg/status

Thanks 
Geoff

**Comment by geoffr** [comment]
Just FYI I am running this on Debian 10 (Buster) successfully otherwise, I mention this as the supported version doesn't currently include 10

**Comment by ju5t** [comment]
I am not sure how to do this as I am not a Debian user myself and neither are we @sensson. If you're able to make this, feel free to raise a PR.

As support for Debian 10 goes, we don't keep track of all operating systems and we do rely on users like yourself to notify us of these changes. Is what you're describing an overall issue with Debian or is it safe to assume Debian 10 is fully supported? In that case we will add it to our supported systems.

**Comment by geoffr** [comment]
I will create PR. its not really an issue its just that sometimes pinning priority of other package repos is high than the 600 in this module which means we ended up with the Debian version of PowerDNS and they do tend to lag quite far behind and in our case the version or 4.1 they provide has issues with DNSSEC queries so I would like to force using the packages from PowerDNS themselves.

BTW Thanks for the module :)
