### ISSUE TITLE
disable ipv6

### ISSUE THREAD

**Issue by tepecat** [sensson/puppet-powerdns#76]
Hey,
I would like set local-ipv6 to nothing, because I dont want use ipv6 for pdns service.

so I set follow in my hiera definition:
`powerdns::auth::config:
     'local-ipv6':
        value: '' 
`
I need follow config line inside /etc/powerdns/pdns.conf
 
`local-ipv6=`
But I get follow error:
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Value for local-ipv6 can't be empty. (file: /etc/puppetlabs/code/modules/powerdns/manifests/config.pp, line: 11, column: 7) (file: /etc/puppetlabs/code/modules/powerdns/manifests/init.pp, line: 53)

solution could be to add exception for local-ipv6 in config.pp

`unless $ensure == 'absent' or ($setting in [ 'gmysql-dnssec', 'only-notify', 'allow-notify-from','local-ipv6' ]) {
    assert_type(Variant[String[1], Integer], $value) |$_expected, $_actual| {
      fail("Value for ${setting} can't be empty.")
    }
  }
`

**Comment by ju5t** [comment]
If this setting can be empty feel free to add it through a pull request.

Note that this setting is not available anymore since 4.4, it has been deprecated in 4.3.
