### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by hostingnuggets** [sensson/puppet-powerdns#77]
On Debian 10 with a puppet master 5.5.10 it is currently not possible to install version 1.7.1 or this puppet module:
```
$ sudo puppet module install sensson-powerdns --version 1.7.1
Notice: Preparing to install into /etc/puppet/code/environments/production/modules ...
Notice: Downloading from https://forgeapi.puppet.com ...
Error: Could not install module 'sensson-powerdns' (???)
  No version of 'sensson-powerdns' can satisfy all dependencies
    Use `puppet module install --ignore-dependencies` to install only this module
```

It looks like the dependencies of this module is not up to date which prevents the installation. For example this modules requires puppetlabs/apt (>=2.0.0 < 7.0.0) and I have puppetlabs/apt version 7.5.0 installed.

My dependencies look like that:
```
├── puppetlabs-stdlib (v6.3.0)
├── puppetlabs-mysql (v10.8.0)
├── puppetlabs-postgresql (v6.8.0)
├── puppetlabs-apt (v7.5.0)
```

**Comment by ju5t** [comment]
@hostingnuggets feel free to bump apt, I doubt this has any backwards incompatibilities.
