### ISSUE TITLE
Puppet module dependency for epel

### ISSUE THREAD

**Issue by geoffr** [sensson/puppet-powerdns#82]
Hi,

The stahnma/epel forge module has been deprecated and the suggested replacement is puppet/epel , could you perhaps switch the metadata file?  The module was taken over by voxpopuli so its functionally the same.

Thanks

**Comment by ju5t** [comment]
@geoffr feel free to open PR's for such changes. We don't always have the time to immediately look at such requests, even when they seem small.

**Comment by ju5t** [comment]
It's in develop now. Will release a new version in the new year.

**Comment by geoffr** [comment]
Thanks very much and apologies I was on vacation and would have looked at a PR when back
