### ISSUE TITLE
Repo's not being created on clean CentOS 7 installation.

### ISSUE THREAD

**Issue by jameskirsop** [sensson/puppet-powerdns#87]
Related to #64, I'm calling the example manifest:
```
class { 'powerdns':
  db_password      => 's0m4r4nd0mp4ssw0rd',
  db_root_password => 'v3rys3c4r3',
}
```
with the passwords substituted, but the repo's are not being created, and I'm seeing the mysql-related error.

If I read correctly, [according to `init.pp` the first thing that should happen is that the repos are created on disk](https://github.com/sensson/puppet-powerdns/blob/7a5ff535e3fcd318cfc37404c016916ef3e27a9f/manifests/init.pp#L42) (nothing in /etc/yum.repos.d). I'm not able to work out why.

In this instance, an issue like the one represented in #64 is going to occur because there's no schema file on the disk for it to load - regardless of mysql permissions.

**Comment by ju5t** [comment]
If you run the agent in debug mode, do you see any `Powerdns::Repo` (case sensitive) references flying by?

I just did the following test (locally) using Vagrant:

```bash
bundle exec rake spec_prep
BEAKER_destroy=onpass BEAKER_PUPPET_COLLECTION=puppet5 bundle exec rake beaker:centos7
```

You should be seeing:

```
  Notice: /Stage[main]/Powerdns::Repo/Package[yum-plugin-priorities]/ensure: created
  Notice: /Stage[main]/Powerdns::Repo/Yumrepo[powerdns]/ensure: created
  Info: Yumrepo[powerdns](provider=inifile): changing mode of /etc/yum.repos.d/powerdns.repo from 600 to 644
  Notice: /Stage[main]/Powerdns::Repo/Yumrepo[powerdns-recursor]/ensure: created
  Info: Yumrepo[powerdns-recursor](provider=inifile): changing mode of /etc/yum.repos.d/powerdns-recursor.repo from 600 to 644
```

The test build itself crashed by the way, not sure why, beaker and Vagrant isn't great. 

However, when I ssh into the box I do see the file there:

```bash
# ls | grep powerdns
powerdns-recursor.repo
powerdns.repo
```

From what I have seen so far #64 is a different issue. 

If you don't want to manage the MySQL service itself you can turn it off by setting `backend_install` to false. That way you can install MySQL yourself and pass the password to the service for it to install the PowerDNS database.

To do that, you need the repo to be there, but I don't know why that isn't working for you without some more details. As far as I can tell at the moment and as the tests show, everything seems to be working as it should.

**Comment by jameskirsop** [comment]
On my node where I'm trying to deploy I'm getting the following:

```
$ sudo puppet agent -d --test | grep ower
...
Debug: /Stage[main]/Mysql::Server::Root_password/before: before to Mysql::Db[powerdns]
Debug: /Stage[main]/Powerdns::Repo/Package[yum-plugin-priorities]/before: before to Yumrepo[powerdns]
Debug: /Stage[main]/Powerdns::Repo/Yumrepo[powerdns]/before: before to Package[pdns]
Debug: /Stage[main]/Powerdns::Backends::Mysql/Package[pdns-backend-mysql]/require: require to Package[pdns]
Debug: /Stage[main]/Powerdns::Backends::Mysql/Package[pdns-backend-mysql]/before: before to Service[pdns]
Debug: /Stage[main]/Powerdns::Backends::Mysql/Mysql::Db[powerdns]/require: require to Package[pdns-backend-mysql]
Debug: /Stage[main]/Powerdns::Authoritative/Service[pdns]/require: require to Package[pdns]
Debug: /Stage[main]/Powerdns::Backends::Mysql/Powerdns::Config[launch]/File_line[powerdns-config-launch-/etc/pdns/pdns.conf]/require: require to Package[pdns]
Debug: /Stage[main]/Powerdns::Backends::Mysql/Powerdns::Config[launch]/File_line[powerdns-config-launch-/etc/pdns/pdns.conf]/notify: notify to Service[pdns]
Debug: /Stage[main]/Powerdns::Backends::Mysql/Powerdns::Config[gmysql-host]/File_line[powerdns-config-gmysql-host-/etc/pdns/pdns.conf]/require: require to Package[pdns]
Debug: /Stage[main]/Powerdns::Backends::Mysql/Powerdns::Config[gmysql-host]/File_line[powerdns-config-gmysql-host-/etc/pdns/pdns.conf]/notify: notify to Service[pdns]
Debug: /Stage[main]/Powerdns::Backends::Mysql/Powerdns::Config[gmysql-port]/File_line[powerdns-config-gmysql-port-/etc/pdns/pdns.conf]/require: require to Package[pdns]
Debug: /Stage[main]/Powerdns::Backends::Mysql/Powerdns::Config[gmysql-port]/File_line[powerdns-config-gmysql-port-/etc/pdns/pdns.conf]/notify: notify to Service[pdns]
Debug: /Stage[main]/Powerdns::Backends::Mysql/Powerdns::Config[gmysql-user]/File_line[powerdns-config-gmysql-user-/etc/pdns/pdns.conf]/require: require to Package[pdns]
Debug: /Stage[main]/Powerdns::Backends::Mysql/Powerdns::Config[gmysql-user]/File_line[powerdns-config-gmysql-user-/etc/pdns/pdns.conf]/notify: notify to Service[pdns]
Debug: /Stage[main]/Powerdns::Backends::Mysql/Powerdns::Config[gmysql-password]/File_line[powerdns-config-gmysql-password-/etc/pdns/pdns.conf]/require: require to Package[pdns]
Debug: /Stage[main]/Powerdns::Backends::Mysql/Powerdns::Config[gmysql-password]/File_line[powerdns-config-gmysql-password-/etc/pdns/pdns.conf]/notify: notify to Service[pdns]
Debug: /Stage[main]/Powerdns::Backends::Mysql/Powerdns::Config[gmysql-dbname]/File_line[powerdns-config-gmysql-dbname-/etc/pdns/pdns.conf]/require: require to Package[pdns]
Debug: /Stage[main]/Powerdns::Backends::Mysql/Powerdns::Config[gmysql-dbname]/File_line[powerdns-config-gmysql-dbname-/etc/pdns/pdns.conf]/notify: notify to Service[pdns]
Debug: /Stage[main]/Powerdns::Backends::Mysql/Mysql::Db[powerdns]/Mysql_database[powerdns]/require: require to Class[Mysql::Client]
Debug: /Stage[main]/Powerdns::Backends::Mysql/Mysql::Db[powerdns]/Mysql_grant[powerdns@localhost/powerdns.*]/require: require to Mysql_database[powerdns]
Debug: /Stage[main]/Powerdns::Backends::Mysql/Mysql::Db[powerdns]/Mysql_grant[powerdns@localhost/powerdns.*]/require: require to Mysql_user[powerdns@localhost]
Debug: /Stage[main]/Powerdns::Backends::Mysql/Mysql::Db[powerdns]/Exec[powerdns-import]/require: require to Mysql_grant[powerdns@localhost/powerdns.*]
Debug: /Stage[main]/Powerdns::Backends::Mysql/Mysql::Db[powerdns]/Exec[powerdns-import]/subscribe: subscribe to Mysql_database[powerdns]
...
```

Accordingly, `ls /etc/yum.repos.d/ | grep powerdns` gives me no results.

I thought the purpose of `backend_install` was to also setup the database schema (tables etc), not just install MySQL. Perhaps this should be split in to two, for circumstances where you want the module to setup the schema but not install the database engine?

**Comment by jameskirsop** [comment]
Update, I've created a new host and a manifest with only the pdns class. This works (however, it takes two puppet runs to complete without error).

I've also added set `backend_install` to false on the original test host with no success.

So, I'm now figuring out why the [puppet-zabbix](https://github.com/voxpupuli/puppet-zabbix) module / classes and this pdns won't work together. The goal is to have both running on the same server. The manifest for the host is pretty bare, just installs Zabbix Server, Zabbix Web + Apache/mySQL and manages some firewalld rules...

**Comment by ju5t** [comment]
> I thought the purpose of backend_install was to also setup the database schema (tables etc), not just install MySQL. Perhaps this should be split in to two, for circumstances where you want the module to setup the schema but not install the database engine?

They already are. See: [backend_create_tables](https://github.com/sensson/puppet-powerdns/tree/7a5ff535e3fcd318cfc37404c016916ef3e27a9f#backend_create_tables) in the README and [mysql.pp#L67](https://github.com/sensson/puppet-powerdns/blob/7a5ff535e3fcd318cfc37404c016916ef3e27a9f/manifests/backends/mysql.pp#L67).

> So, I'm now figuring out why the puppet-zabbix module / classes and this pdns won't work together. The goal is to have both running on the same server. The manifest for the host is pretty bare, just installs Zabbix Server, Zabbix Web + Apache/mySQL and manages some firewalld rules...

We're using the same package for our monitoring, but we're only installing the agent. Not the server as well.
