### ISSUE TITLE
Usage of version 4.4 not possible due to validation

### ISSUE THREAD

**Issue by regiohelden-dev** [sensson/puppet-powerdns#89]
The most recent release of PowerDNS is 4.4 (see https://www.powerdns.com/downloads.html), but in https://github.com/sensson/puppet-powerdns/blob/a3801785c09395642b5701ecd752b59bd396041c/manifests/init.pp#L22 it will be rejected as 4.4 isn't matching the pattern.

Instead of validating for a specific version number, I'd just validate how the version number should look:
```
Pattern[/4\.[0-9]+/]    $version                            = $::powerdns::params::version,
```

**Comment by regiohelden-dev** [comment]
I'm happy to send a PR for this change

**Comment by ju5t** [comment]
Feel free to open a PR for this. Happy to merge.

**Comment by saz** [comment]
See #95 to add support for powerdns 4.4
