### ISSUE TITLE
Dependency cycle if apt repo is managed

### ISSUE THREAD

**Issue by regiohelden-dev** [sensson/puppet-powerdns#90]
Due to https://github.com/sensson/puppet-powerdns/blob/a3801785c09395642b5701ecd752b59bd396041c/manifests/repo.pp#L62 a run results in a dependency cycle, if you're using `apt::ppa` and the `package_manage => true` is set on `apt:ppa`:

```
Error: Found 1 dependency cycle:                                                                     
(Exec[add-apt-repository-ppa:ondrej/php] => Class[Apt::Update] => Exec[apt_update] => Class[Apt::Update] => Package[software-properties-common] => Exec[add-apt-repository-ppa:ondrej/php])\nTry the '--gra
ph' option and opening the resulting '.dot' file in OmniGraffle or GraphViz                          
Error: Failed to apply catalog: One or more resource dependency cycles detected in graph
```

If `package_manage` is set to `true`, the `software-properties-common` package will be installed, but this is now having a dependency on `Class['apt::update']`...

See https://github.com/puppetlabs/puppetlabs-apt/blob/8ab173b701246eae04611157057e787817cf3897/manifests/ppa.pp#L67 and https://github.com/puppetlabs/puppetlabs-apt/blob/8ab173b701246eae04611157057e787817cf3897/manifests/ppa.pp#L83-L91

**Comment by regiohelden-dev** [comment]
Deleting line 62 in repo.pp will resolve this issue and works without a problem as the `apt` module is handling everything

**Comment by ju5t** [comment]
Is the apt module handling this regardless of whether or not you're using `apt::ppa`? If it does, I would be happy to merge a PR, but in this case I would be keen on having some tests that cover it this case.

**Comment by saz** [comment]
Looking at https://forge.puppet.com/modules/puppetlabs/apt#update-the-list-of-packages:
```
By default, Puppet runs apt-get update on the first Puppet run after you include the apt class, and anytime notify => Exec['apt_update'] occurs; i.e., whenever config files get updated or other relevant changes occur. If you set update['frequency'] to 'always', the update runs on every Puppet run. You can also set update['frequency'] to 'daily' or 'weekly
```
As the apt module is intended to manage apt repos, I don't see a reason to validate that behavior within this module.

Or are you speaking of other kind of tests?

**Comment by ju5t** [comment]
Ok, so the update runs when:

- `notify => Exec['apt_update']` is called, which only happens when something in `apt` changes.
- if you have set the update frequency in `apt`.

I think the `notify` option is the only sensible one as it doesn't require the user to do anything extra.

This means it's not as easy as removing that line. It would solve it for you, but other users will most likely run into problems.

**Comment by saz** [comment]
You just need to add `require => Apt::Source['powerdns']` to solve this issue to the package resource.

It's working for all of my modules I'm maintaining. If you're using puppet to manage sudo or memcached, chances are good you're using my modules https://forge.puppet.com/saz

I'll create a pull request for that, to show my point.

**Comment by ju5t** [comment]
I knew your name sounded familiar. As long as it works for all operating systems that's fine.

**Comment by saz** [comment]
I'll send the pr in a few hours. Btw expect a couple of more pr from me :)

**Comment by ju5t** [comment]
@saz thanks, it's always appreciated!

<sup>And also thanks for the modules you make. We're a happy user of some (I checked, we're using your ssh and timezone module).</sup>
